---
title: 'Assignment 3: Almond Profit Sensitivity'
author: "Allie Cole, Halina Do-Linh, Jake Eisaguirre"
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set up
knitr::opts_chunk$set(echo = TRUE) #,
                      #message = FALSE,
                      #warning = FALSE)

# attached packages
librarian::shelf(
  tidyverse,
  here,
  janitor,
  patchwork
)

# source necessary functions
source(here("hw/functions/almond_profit.R"))
source(here("hw/functions/compute_npv.R"))

# read in data
almond_yield_data <- read_csv(here("hw/data/annual_almond_yield.csv")) %>% 
  select(-c(mean_precip_jan, mean_tmin_c_feb))
```

# Assignment 3

1. Develop a profit model for your almond yield (you can make this up - think about what the parameters would be)

```{r}
# test model

profit_almond = almond_profit(almond_yield_anomaly = almond_yield_data$almond_yield_pct,
                              year = almond_yield_data$year,
                              price = 10,
                              discount = 0.12)
```

2. Do a simple informal sensitivity analysis of almond yield profit using at least 2 parameters

```{r}
deviation_price = 1
base_price = 10

deviation_discount = 0.1
base_discount = 0.5

price = runif(min = 1,
              max = base_price + deviation_price * base_price,
              n = 300)

discount = runif(min = 1,
                 max = deviation_price + deviation_discount * base_discount,
                 n = 300)

parms <- cbind.data.frame(price, discount) 

profit_almond_1 =  parms %>% pmap(almond_profit,
                                  almond_yield_anomaly = almond_yield_data$almond_yield_pct,
                                  year = almond_yield_data$year)



mean_price = map(profit_almond_1, c("net"))

clean_data <- as.data.frame(mean_price) %>% 
  mutate(year = c(1989:2010)) %>% 
  pivot_longer(cols = starts_with("c."), values_to = "net") %>% 
  select(!(name)) %>% 
  filter(net >0) # no farmer would give money to a customer

```

3. Create a single graph of the results - you can decide what is the most meaningful graph
4. Output the graph as a stand alone image (pdf, tiff, jpeg)

```{r}

ggplot(clean_data, aes(as.factor(year), net)) +
  geom_boxplot() +
  labs(title = "Almond Profit from 1998-2010") +
  xlab( "Year") +
  ylab("Net Profit $") +
  theme_minimal()

ggsave(here("almond_profit_plot.png"))

```

